plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.maven.publish)
}

// The version the reporter puts in every report.
//
// The JVM siblings read it from the jar manifest via Package.getImplementationVersion(),
// which returns NULL on Android: dex has no per-package manifest, so
// addDefaultImplementationEntries has nothing to attach to. Left alone, every report would
// claim 0.0.0-dev -- which junit5 actually shipped once, in a real release.
//
// So it is generated into a source file instead. buildConfigField was the alternative; a
// generated class avoids turning on buildFeatures.buildConfig for one string.
version = "0.1.0"

abstract class GenerateVersion : DefaultTask() {
    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = outputDir.get().asFile.resolve("com/qualflare/espresso")
        pkg.mkdirs()
        pkg.resolve("Version.java").writeText(
            """
            package com.qualflare.espresso;

            /** Generated by the build. Never edit: see GenerateVersion in build.gradle.kts. */
            final class Version {
                static final String VALUE = "${version.get()}";

                private Version() {}
            }
            """.trimIndent() + "\n"
        )
    }
}

val generateVersion = tasks.register<GenerateVersion>("generateVersion") {
    version.set(project.version.toString())
    outputDir.set(layout.buildDirectory.dir("generated/qualflare/java"))
}

android {
    namespace = "com.qualflare.espresso"
    compileSdk = 36

    defaultConfig {
        // 24, not 21: java.util.function is available here, which the ported code
        // uses. java.time, java.util.Base64 and all of java.nio.file are API 26+
        // and are deliberately absent from src/main -- see the lint config below,
        // which makes reintroducing them a build failure rather than a runtime
        // crash on someone's phone.
        minSdk = 24
        consumerProguardFiles("consumer-rules.pro")
    }

    compileOptions {
        // Java 11 bytecode, matching the two JVM sibling reporters.
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    lint {
        // NewApi as an error is the guard rail for minSdk 24. Core library
        // desugaring would hide these, but that is a CONSUMER setting an AAR
        // cannot assume, so the library must not rely on it.
        error += "NewApi"
        abortOnError = true
        warningsAsErrors = false
        checkReleaseBuilds = true
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
            all {
                // VersionTest compares the generated constant against this, so a build that
                // forgets to regenerate it fails rather than shipping a stale version -- the
                // failure mode that put 0.0.0-dev in a real junit5 release.
                it.systemProperty("qualflare.expectedVersion", project.version.toString())

                // SampleReportTest writes build/sample-report, which tools/verify.py then
                // checks in CI. Declaring it as an OUTPUT of the test task is what makes that
                // reliable: without this the directory is an undeclared side effect, so a task
                // restored from the build cache never produces it and the verify step fails on
                // a clean runner with "nothing reached the host" -- which is exactly what
                // happened. Declared, the cache restores it along with the test results.
                it.outputs.dir(layout.buildDirectory.dir("sample-report"))
            }
        }
    }

}

// CI compiles against the androidx.test floor as well as the current version:
// -Pqualflare.monitorVersion=1.4.0. 1.4.0 is the first release carrying
// androidx.test.platform.io.PlatformTestStorage, and since the library's
// dependencies are compileOnly, whatever the consumer resolves is what runs.
val monitorOverride: String? = providers.gradleProperty("qualflare.monitorVersion").orNull

configurations.configureEach {
    if (monitorOverride != null) {
        resolutionStrategy.eachDependency {
            if (requested.group == "androidx.test" && requested.name == "monitor") {
                useVersion(monitorOverride)
                because("CI floor check: -Pqualflare.monitorVersion")
            }
        }
    }
}

dependencies {
    // compileOnly throughout, the AAR-shaped equivalent of the siblings' <scope>provided</scope>.
    // Publishing a version constraint on androidx.test would invite NoSuchMethodError
    // against whatever Espresso BOM the consumer already has.
    compileOnly(libs.junit)
    compileOnly(libs.androidx.test.monitor)
    compileOnly(libs.androidx.test.runner)
    compileOnly(libs.espresso.core)

    testImplementation(libs.junit)
    testImplementation(libs.truth)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.monitor)
    testImplementation(libs.androidx.test.runner)
    testImplementation(libs.espresso.core)
}

// The generated source has to reach EVERY variant's compile, with the task dependency
// carried along. android.sourceSets { java.srcDir(task) } does not do that: it compiled
// locally only because an earlier direct invocation had left the file on disk, and a clean
// build failed with "cannot find symbol Version". addGeneratedSourceDirectory is AGP's
// supported route and wires the dependency itself.
androidComponents {
    onVariants { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(generateVersion, GenerateVersion::outputDir)
    }
}

// Publishing to Maven Central through the Central Portal.
//
// None of the Maven siblings' publishing carries over: no central-publishing-maven-plugin, no
// maven-gpg-plugin (Gradle's signing never touches a TTY, so there is no --pinentry-mode
// loopback to arrange), no maven-source-plugin or maven-javadoc-plugin. What does carry over is
// everything that is a decision rather than a mechanism -- the pom block, publishing under a
// human gate, and the refusal to release a SNAPSHOT.
mavenPublishing {
    // Uploaded, validated, and then left sitting in the portal until a human presses release.
    // The Maven siblings make the same call for the same reason: nothing about a deployment is
    // reversible once it is on Central.
    publishToMavenCentral(automaticRelease = false)
    // Central rejects an unsigned artifact outright, and the failure surfaces at the end of a
    // release rather than the start.
    signAllPublications()

    // The platform is left to the plugin, which for com.android.library publishes the `release`
    // variant with a sources jar and a javadoc jar. Those three are asserted by the release
    // workflow rather than taken on trust, because AGP has no equivalent of
    // maven-source-plugin to fall back on if the default ever changes.

    coordinates("com.qualflare", "qualflare-espresso", project.version.toString())

    pom {
        name.set("qualflare-espresso")
        description.set(
            "Native Espresso reporter for Qualflare -- runs inside the instrumented app and " +
                "captures status, retry history, steps, screenshots and author-facing metadata " +
                "straight from the device."
        )
        url.set("https://qualflare.com/espresso-test-reporting/")
        licenses {
            license {
                name.set("Apache-2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                name.set("Qualflare")
                email.set("ibrahim@qualflare.com")
                organization.set("Qualflare")
                organizationUrl.set("https://qualflare.com")
            }
        }
        scm {
            url.set("https://github.com/Qualflare/qualflare-espresso")
            connection.set("scm:git:https://github.com/Qualflare/qualflare-espresso.git")
            developerConnection.set("scm:git:git@github.com:Qualflare/qualflare-espresso.git")
        }
    }
}

// The release workflow asserts that the git tag matches this, before anything is uploaded --
// a wrong version on Maven Central is permanent. A task rather than `gradle properties`, which
// prints a hundred lines and would hide the one that matters.
tasks.register("printVersion") {
    val resolved = project.version.toString()
    doLast { println(resolved) }
}
